pub const NEWSWEEK_100_BOOKS: [&str; 101] =[
    "War and Peace", 
    "1984", 
    "Ulysses", 
    "Lolita", 
    "The Sound and the Fury", 
    "Invisible Man", 
    "To the Lighthouse", 
    "Iliad", 
	"Odyssey", 
    "Pride and Prejudice", 
    "Divine Comedy", 
    "The Canterbury Tales", 
    "Gulliver's Travels", 
    "Middlemarch", 
    "Things Fall Apart", 
    "The Catcher in the Rye", 
    "Gone With the Wind", 
    "One Hundred Years of Solitude", 
    "The Great Gatsby", 
    "Catch-22", 
    "Beloved", 
    "The Grapes of Wrath", 
    "Midnight's Children", 
    "Brave New World", 
    "Mrs. Dalloway", 
    "Native Son", 
    "Democracy in America", 
    "The Origin of Species",
    "The Histories", 
    "The Social Contract", 
    "Das Kapital", 
    "The Prince", 
    "Confessions", 
    "Leviathan", 
    "The History of the Peloponnesian War", 
    "Lord of the Rings", 
    "Winnie-The-Pooh", 
    "Lion, the Witch, and the Wardrobe", 
    "A Passage to India", 
    "On the Road", 
    "To Kill a Mockingbird", 
    "Holy Bible", 
    "A Clockwork Orange", 
    "Light in August", 
    "The Souls of Black Folk", 
    "Wide Sargasso Sea", 
    "Madame Bovary", 
    "Paradise Lost", 
    "Anna Karenina", 
    "Hamlet", 
    "King Lear", 
    "Othello", 
    "The Sonnets of William Shakespeare", 
    "Leaves of Grass", 
    "The Adventures of Huckleberry Finn", 
    "Kim", 
    "Frankenstein", 
    "Song of Solomon", 
    "One Flew Over the Cuckoo's Nest", 
    "For Whom the Bell Tolls", 
    "Slaughter-House-Five", 
    "Animal Farm", 
    "Lord of the Flies", 
    "In Cold Blood", 
    "The Golden Notebook", 
    "Remembrance of Things Past", 
    "The Big Sleep", 
    "As I Lay Dying", 
    "The Sun Also Rises", 
    "I, Claudius", 
    "The Heart Is a Lonely Hunter", 
    "Sons and Lovers", 
    "All the King's Men", 
    "Go Tell It on the Mountain", 
    "Charlotte's Web", 
    "Heart of Darkness", 
    "Night", 
    "Rabbit, Run", 
    "The Age of Innocence", 
    "Portnoy's Complaint", 
    "An American Tragedy", 
    "The Day of the Locust", 
    "Tropic of Cancer", 
    "The Maltese Falcon", 
    "His Dark Materials", 
    "Death Comes for the Archbishop", 
    "The Interpretation of Dreams", 
    "The Education of Henry Adams", 
    "Quotations From Chairman Mao", 
    "The Varieties of Religious Experience", 
    "Brideshead Revisited", 
    "Silent Spring", 
    "The General Theory of Employment, Interest, and Money", 
    "Lord Jim", 
    "Goodbye to All That", 
    "The Affluent Society", 
    "The Wind in the Willows", 
    "The Autobiography of Malcolm X", 
    "Eminent Victorians", 
    "The Color Purple", 
    "The Second World War"
];
